[package]
authors = ["Willem Wyndham <willem@ahalabs.dev>"]
description = "Tools for generating to and from wit format"
edition = "2021"
keywords = ["WebAssembly", "Wasm", "wit", "WasmInterfaceTypes"]
license = "MIT"
name = "witme"
repository = "https://github.com/ahalabs/witme"
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
cargo_metadata = "0.14.1"
clap = "=3.0.0-beta.5"
clap_derive = "=3.0.0-beta.5"
glob = "0.3.0"
once_cell = "1.8.0"
aha-wit-parser = {git="https://github.com/ahalabs/wit-bindgen", rev="7cff7a3173d82ac14313d972737c476790fff217"}
wit-bindgen-gen-js-near = {git="https://github.com/ahalabs/wit-bindgen", rev="7cff7a3173d82ac14313d972737c476790fff217"}
aha-wit-bindgen-gen-core = {git="https://github.com/ahalabs/wit-bindgen", rev="7cff7a3173d82ac14313d972737c476790fff217"}


[workspace]
members = ["examples/*"]
